### ISSUE TITLE
errors while training 

### ISSUE THREAD

**Issue by byuns9334** [b04901014/waveglow-tensorflow#5]
Hi, I finished procaudio.py and now trying to run main.py. But I get this error: could you help with this? Thanks in advance!

WARNING: Logging before flag parsing goes to stderr.
W0805 11:26:09.772453 139742458730240 deprecation_wrapper.py:119] From main.py:2: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

/usr/local/lib/python3.5/dist-packages/numba/errors.py:131: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
W0805 11:26:10.160339 139742458730240 deprecation_wrapper.py:119] From main.py:34: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0805 11:26:10.161276 139742458730240 deprecation_wrapper.py:119] From main.py:23: The name tf.GPUOptions is deprecated. Please use tf.compat.v1.GPUOptions instead.

W0805 11:26:10.161381 139742458730240 deprecation_wrapper.py:119] From main.py:24: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0805 11:26:10.161485 139742458730240 deprecation_wrapper.py:119] From main.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-08-05 11:26:10.161679: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-08-05 11:26:10.166440: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-08-05 11:26:11.349611: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-05 11:26:11.360762: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-05 11:26:11.361384: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5c75250 executing computations on platform CUDA. Devices:
2019-08-05 11:26:11.361393: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080, Compute Capability 6.1
2019-08-05 11:26:11.361396: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): GeForce GTX 1080, Compute Capability 6.1
2019-08-05 11:26:11.363259: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408080000 Hz
2019-08-05 11:26:11.363425: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5cf2890 executing computations on platform Host. Devices:
2019-08-05 11:26:11.363436: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-05 11:26:11.364043: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-05 11:26:11.364481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8095
pciBusID: 0000:01:00.0
2019-08-05 11:26:11.364557: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-05 11:26:11.364981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8095
pciBusID: 0000:02:00.0
2019-08-05 11:26:11.365079: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2019-08-05 11:26:11.365144: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2019-08-05 11:26:11.365194: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2019-08-05 11:26:11.365253: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2019-08-05 11:26:11.365311: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2019-08-05 11:26:11.365380: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2019-08-05 11:26:11.367616: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-05 11:26:11.367631: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2019-08-05 11:26:11.367666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-05 11:26:11.367673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 
2019-08-05 11:26:11.367677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N Y 
2019-08-05 11:26:11.367680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   Y N 
W0805 11:26:11.368261 139742458730240 deprecation_wrapper.py:119] From /home/users/woody/waveglow/waveglow-tensorflow/src/model.py:16: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

Time Segments of audio for training: 16384
Total number of parameters: 268294760
Total number of audio/text pair for training: 11790
W0805 11:26:22.729164 139742458730240 deprecation_wrapper.py:119] From /home/users/woody/waveglow/waveglow-tensorflow/src/model.py:61: The name tf.train.exponential_decay is deprecated. Please use tf.compat.v1.train.exponential_decay instead.

W0805 11:26:22.734666 139742458730240 deprecation_wrapper.py:119] From /home/users/woody/waveglow/waveglow-tensorflow/src/model.py:65: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

W0805 11:26:22.906246 139742458730240 deprecation.py:323] From /home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/ops/math_grad.py:1205: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0805 11:26:46.083026 139742458730240 deprecation_wrapper.py:119] From /home/users/woody/waveglow/waveglow-tensorflow/src/model.py:69: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2019-08-05 11:26:55.885543: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
W0805 11:26:58.329224 139742458730240 deprecation_wrapper.py:119] From /home/users/woody/waveglow/waveglow-tensorflow/src/model.py:82: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

W0805 11:26:58.330414 139742458730240 deprecation_wrapper.py:119] From /home/users/woody/waveglow/waveglow-tensorflow/src/model.py:84: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

W0805 11:26:58.333762 139742458730240 deprecation_wrapper.py:119] From /home/users/woody/waveglow/waveglow-tensorflow/src/model.py:88: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

Total number of audio/text pair for validation: 1310
Error Loading Model! Training From Initial State...

  0%|          | 0/5 [00:00<?, ?it/s]2019-08-05 11:27:02.720775: E tensorflow/core/common_runtime/executor.cc:641] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropInputOp only supports NHWC.
	 [[{{node upsample/conv2d_transpose}}]]

Traceback (most recent call last):
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
	 [[{{node upsample/conv2d_transpose}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/woody/waveglow/waveglow-tensorflow/src/model.py", line 159, in sample
    output = self.sess.run(self.output, feed_dict={self.mels: [mels]})
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
	 [[node upsample/conv2d_transpose (defined at /home/users/woody/waveglow/waveglow-tensorflow/src/ops.py:42) ]]

Errors may have originated from an input operation.
Input Source operations connected to node upsample/conv2d_transpose:
 upsample/weights/read (defined at /home/users/woody/waveglow/waveglow-tensorflow/src/ops.py:19)	
 ExpandDims (defined at /home/users/woody/waveglow/waveglow-tensorflow/src/ops.py:54)

Original stack trace for 'upsample/conv2d_transpose':
  File "main.py", line 34, in <module>
    tf.app.run()
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/users/woody/.local/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/users/woody/.local/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 27, in main
    model = WaveGlow(sess)
  File "/home/users/woody/waveglow/waveglow-tensorflow/src/model.py", line 13, in __init__
    self.build_model()
  File "/home/users/woody/waveglow/waveglow-tensorflow/src/model.py", line 20, in build_model
    self.conditions = mydeconv1d(self.mels, args.n_mel, filter_size=args.step_per_mel*4, stride=args.step_per_mel, scope='upsample', reuse=False)
  File "/home/users/woody/waveglow/waveglow-tensorflow/src/ops.py", line 55, in mydeconv1d
    ret = mydeconv2d(inputs, output_channel, filter_size, strides, scope, reuse)
  File "/home/users/woody/waveglow/waveglow-tensorflow/src/ops.py", line 42, in mydeconv2d
    deconv = tf.nn.conv2d_transpose(inputs, weights, output_shape=output_shape, strides=strides, data_format="NCHW")
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 2147, in conv2d_transpose
    name=name)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 2218, in conv2d_transpose_v2
    name=name)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1407, in conv2d_backprop_input
    name=name)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/users/woody/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

  0%|          | 0/2947 [00:00<?, ?it/s]

**Comment by Ella77** [comment]
deconv = tf.nn.conv2d_transpose(inputs, weights, output_shape=output_shape, strides=strides, data_format=“NCHW”)  
InvalidArgumentError (see above for traceback): Conv2DCustomBackpropInputOp only supports NHWC 

I've got the same error

**Comment by Ella77** [comment]
`` deconv = tf.nn.conv2d_transpose(inputs, weights, output_shape=output_shape, strides=strides, data_format="NCHW")
        deconv2 = tf.transpose(deconv, [0, 3, 1, 2])
        return tf.nn.bias_add(deconv2, biases, data_format="NCHW")``

**Comment by Ella77** [comment]
https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_transpose I think updated tf version supports it . 
data_format: A string. 'NHWC' and 'NCHW' are supported.
